services:
  php:
    build: .
    container_name: php-container
    ports:
      - "8080:443"
    volumes:
      - ./app:/var/www/html
      - ./app/uploads:/var/www/html/uploads
      - ./certs:/etc/apache2/ssl
    depends_on:
      - mysql
    command: >
      sh -c "
      a2enmod ssl &&
      cp /etc/apache2/sites-available/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf.bak &&
      sed -i 's|SSLCertificateFile.*|SSLCertificateFile /etc/apache2/ssl/selfsigned.crt|' /etc/apache2/sites-available/default-ssl.conf &&
      sed -i 's|SSLCertificateKeyFile.*|SSLCertificateKeyFile /etc/apache2/ssl/selfsigned.key|' /etc/apache2/sites-available/default-ssl.conf &&
      a2ensite default-ssl && docker-php-ext-install mysqli && docker-php-ext-enable mysqli &&
      apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: novelists_db
      MYSQL_USER: a
      MYSQL_PASSWORD: a
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql

volumes:
  mysql-data:
